import React, { useState } from "react";

export default function Disclaimer({ compact = false }) {
  const [dismissed, setDismissed] = useState(
    () => sessionStorage.getItem("disclaimer-dismissed") === "true"
  );

  if (compact) {
    return (
      <div className="px-5 py-3 text-center" style={{ borderTop: "1px solid var(--border)" }}>
        <p className="text-[10px] muted leading-relaxed max-w-4xl mx-auto">
          <span className="font-bold text-yellow-500">⚠ DISCLAIMER:</span>{" "}
          TraderX provides AI-generated predictions, signals, and analysis for{" "}
          <strong>educational and informational purposes only</strong>. Nothing on this platform
          constitutes financial advice, investment advice, or a recommendation to buy or sell any
          security. All predictions are generated by machine learning models and{" "}
          <strong>may be incorrect</strong>. Past performance does not guarantee future results.
          Trading stocks, crypto, and forex involves{" "}
          <strong>substantial risk of loss</strong> and is not suitable for all investors.
          You are solely responsible for your own investment decisions.{" "}
          <strong>TraderX and its developers are not liable</strong> for any financial losses
          incurred as a result of using this platform. Always consult a qualified financial advisor
          before making any investment decisions.
        </p>
      </div>
    );
  }

  if (dismissed) return null;

  return (
    <div className="mx-5 mb-4 rounded-xl p-4 text-xs leading-relaxed"
      style={{ background: "rgba(234,179,8,0.06)", border: "1px solid rgba(234,179,8,0.25)" }}>
      <div className="flex items-start justify-between gap-3">
        <div className="flex items-start gap-2.5">
          <span className="text-yellow-500 text-base shrink-0 mt-0.5">⚠</span>
          <div>
            <p className="font-bold text-yellow-500 mb-1">Important Disclaimer — Please Read</p>
            <p className="muted leading-relaxed">
              TraderX provides AI-generated predictions, signals, and market analysis for{" "}
              <strong className="t2">educational and informational purposes only</strong>.
              Nothing on this platform constitutes financial advice, investment advice, or a
              recommendation to buy or sell any security, cryptocurrency, or financial instrument.
            </p>
            <p className="muted leading-relaxed mt-1.5">
              All predictions are generated by machine learning models trained on historical data
              and <strong className="t2">may be inaccurate or completely wrong</strong>.
              Markets are unpredictable. Past performance does not guarantee future results.
              Trading involves <strong className="t2">substantial risk of loss</strong> and is not
              suitable for all investors. You may lose some or all of your invested capital.
            </p>
            <p className="muted leading-relaxed mt-1.5">
              <strong className="t2">You are solely responsible</strong> for your own trading and
              investment decisions. TraderX, its developers, and contributors are{" "}
              <strong className="t2">not liable for any financial losses</strong> incurred as a
              result of using this platform. Always do your own research and consult a qualified
              financial advisor before investing real money.
            </p>
          </div>
        </div>
        <button
          onClick={() => { sessionStorage.setItem("disclaimer-dismissed", "true"); setDismissed(true); }}
          className="shrink-0 text-yellow-500/60 hover:text-yellow-500 transition-colors text-lg leading-none mt-0.5"
          title="Dismiss">
          ×
        </button>
      </div>
    </div>
  );
}
